# Kubernetes Deployment for whoami Application on Edge Nodes

apiVersion: v1 # API version for PersistentVolumeClaim
kind: PersistentVolumeClaim

metadata: # Metadata for PersistentVolumeClaim
  name: whoami-data

spec: # Specification for PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # 500 MB Virtual Disk
---
apiVersion: apps/v1 # API version for Deployment
kind: Deployment

metadata: # Metadata for Deployment
  name: whoami-app
  labels:
    app: whoami

spec: # Specification for Deployment
  replicas: 2 # Desired for High Availability

  selector: # Selector to match Pods
    matchLabels:
      app: whoami

  template: # Template for Pod creation
    metadata: # Metadata for Pod
      labels:
        app: whoami

      spec: # Specification for Pod
        affinity: # Affinity Rules for scheduling Pods on Edge Nodes
          nodeAffinity:
            preferredDuringSchedulingIgnoreDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values:
                      - edge

        containers: # Container Definition for whoami Application
        - name: whoami
          image: traefik/whoami # Request Detail Returning HTTP Server
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: "/data"
            name: whoami-storage

        volumes: # Volume Definition for PersistentVolumeClaim
        - name: whoami-storage
          persistentVolumeClaim:
            claimName: whoami-data
---
apiVersion: v1 # API version for Service
kind: Service

metadata: # Metadata for Service
  name: whoami-service

spec: # Specification for Service
  selector:
    app: whoami
    
  ports:
  - protocol: TCP # Protocol for Service
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1 # API version for Ingress
kind: Ingress

metadata: # Metadata for Ingress
  name: whoami-ingress

spec: # Specification for Ingress
  rules:
  - host: whoami.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-service
            port:
              number: 80